language: python

python:
    - 2.6
    - 2.7
    - 3.2
    - 3.4

env:
    # Try all python versions with the latest numpy
    - ASTROPY_VERSION=stable NUMPY_VERSION=1.8 SETUP_CMD='test'

matrix:
    include:
        # Doc build test disabled for now
        #- python: 2.7
        #  # opdeps needed because the matplotlib sphinx extension requires them
        #  env: ASTROPY_VERSION=stable NUMPY_VERSION=1.8 SETUP_CMD='build_sphinx -w -n'

        # Try alternate numpy versions
        - python: 2.7
          env: ASTROPY_VERSION=stable NUMPY_VERSION=1.6.2 SETUP_CMD='test'
        - python: 3.2
          env: ASTROPY_VERSION=stable NUMPY_VERSION=1.6.2 SETUP_CMD='test'
        - python: 2.7
          env: ASTROPY_VERSION=stable NUMPY_VERSION=1.5.1 SETUP_CMD='test'

before_install:
    # Use utf8 encoding. Should be default, but this is insurance against
    # future changes
    - export PYTHONIOENCODING=UTF8

    # We do this to make sure we get the dependencies so pip works below
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-numpy cython libatlas-dev liblapack-dev gfortran
    - if [[ $SETUP_CMD == build_sphinx* ]]; then sudo apt-get install -qq python-sphinx graphviz texlive-latex-extra dvipng; fi

install:
    - pip -q install --upgrade "numpy==$NUMPY_VERSION" --use-mirrors
    - pip -q install --upgrade "Cython>=0.18" --use-mirrors
    - if [[ $SETUP_CMD == build_sphinx* ]]; then pip -q install sphinx==1.2.2 --use-mirrors; fi
    - if [[ $SETUP_CMD == build_sphinx* ]]; then pip -q install matplotlib --use-mirrors; fi

    # Different flavors of astropy
    - if [[ $ASTROPY_VERSION == stable ]]; then pip -q install astropy==0.4 --use-mirrors; fi
    #- if [[ $ASTROPY_VERSION == development ]]; then pip -q install git+http://github.com/astropy/astropy.git#egg=astropy --use-mirrors; fi
    # Freeze at certain dev commit
    #- if [[ $ASTROPY_VERSION == development ]]; then pip -q install git+git://github.com/astropy/astropy.git@ef19baf695; fi

script:
    - python setup.py $SETUP_CMD
